# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9be61ad28640fd5a05b4931e3893b647006a4f358b42a1b43b7f8358f928fe3452c2fb14946ec00351e24c65f405fb7fe66559ebd4b2b927e62fe4afb55d2f18

test:
  secret_key_base: 90614f19928ada067cfa40c024aabc1460493737e60558c4feb569c68443c1a388b7102ae514fca3c936ed760c40b6674337536068e2aab64c4d462d21bf95be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
